### 1 DIMENSIONAL ARRAY

In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
arr1

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [10]:
arr2 = np.array([1,2,3,4,5,
                6,7,8,9,0,9])
print(arr2)
type(arr2)
print(arr2.ndim)
arr2.dtype

[1 2 3 4 5 6 7 8 9 0 9]
1


dtype('int64')

In [18]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([10,23,6,43,22,1])
print(arr1)
print(arr2)
print(arr2.ndim)
print(arr2.dtype)

[1 2 3 4 5 6 7]
[10 23  6 43 22  1]
1
int64


array([1, 2, 3, 4, 5, 6, 7])

In [29]:
arr1 = np.array([10,2,34,56,3,12,8.3])
arr2 = np.array((12,67,90,4,6,3,4,5))
print(arr1,arr2)
print("arra1: ",arr1.ndim,"arr2: ",arr2.ndim)
print("arr1dtype:",arr1.dtype, "arr2dtype:",arr2.dtype)

[10.   2.  34.  56.   3.  12.   8.3] [12 67 90  4  6  3  4  5]
arra1:  1 arr2:  1
arr1dtype: float64 arr2dtype: int64


### indexing

In [31]:
print(arr1)
print(arr1[3])
print(arr1[0])
print(arr1[0:])
print(arr1[-1])
print(arr1[3:6])

[10.   2.  34.  56.   3.  12.   8.3]
56.0
10.0
[10.   2.  34.  56.   3.  12.   8.3]
8.3
[56.  3. 12.]


### 2 DIMENSIONAL ARRY

In [7]:
import numpy as np

In [8]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(a)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [17]:
b=np.array([[2,3,4,5,6],
            [5,7,8,9,0]])
print(b)
print(b.dtype)
print(b.ndim)

[[2 3 4 5 6]
 [5 7 8 9 0]]
int64
2


In [23]:
arr1 = np.array([[1,2,3,4,5],[56,4,5,7,8],[1,2,3,4,66],[1.1,45.3,56,5,6]])
print(arr1)
arr1.dtype
arr1.ndim

[[ 1.   2.   3.   4.   5. ]
 [56.   4.   5.   7.   8. ]
 [ 1.   2.   3.   4.  66. ]
 [ 1.1 45.3 56.   5.   6. ]]


2

In [31]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [56]:
print(arr2[0,2:])

[3 4]


In [46]:
print(arr2[1,2:])

[7 8]


In [58]:
arr2[1,3:]

array([8])

In [60]:
arr1 = np.array([[1,2,3,4,5,6],
               [4,5,6,7,1,2],
                [3,4,5,6,7,8]])
print(arr1)

[[1 2 3 4 5 6]
 [4 5 6 7 1 2]
 [3 4 5 6 7 8]]


In [62]:
print(arr1.dtype)

int64


In [64]:
print("dimension:",arr1.ndim)

dimension: 2


In [73]:
print(arr1[1,3:])

[7 1 2]


In [75]:
arr1[:]

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 1, 2],
       [3, 4, 5, 6, 7, 8]])

In [81]:
arr1[0:2,3]

array([4, 7])

### 3 DIMENSION ARRAY

In [84]:
sample = np.array([[[2,3,4,5]]])
print(sample)
sample

[[[2 3 4 5]]]


array([[[2, 3, 4, 5]]])

### ARRAY INITIALIZATION

### zero array

In [85]:
import numpy as np

In [90]:
arr1 = np.zeros([3,3])
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [91]:
arr1.dtype

dtype('float64')

In [92]:
arr1.ndim

2

In [96]:
arr2 = np.ones([4,4])
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [94]:
arr2.ndim

2

#### use range

In [99]:
a = np.arange(1,10,3)
a

array([1, 4, 7])

In [100]:
arr1 = np.arange(10,0,-2)
arr1


array([10,  8,  6,  4,  2])

In [101]:
a = np.full((3,4),4)
a

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

### DIAGONAL MATRIX

In [107]:
z = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print(z)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [111]:
z[[0,1,2,3],[0,1,2,3]]=1
print(z)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [3]:
import numpy as np


In [4]:
a = np.zeros((4,4))
print(a)
a[[0,1,2,3],[0,1,2,3]]=3
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]


In [5]:
a[[0,1,2,3],[0,1,2,3]]=2
a

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [7]:
b = np.ones([3,3])
b[[0,1,2],[0,1,2]] = 0
print(b)

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [9]:
b[[0,1,2],[0,1,2]] = 0
b

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

### LINSPACE

In [10]:
a = np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [14]:
b = np.linspace(1,10,12)
b

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [16]:
c = np.linspace(-1,-5,10)
c

array([-1.        , -1.44444444, -1.88888889, -2.33333333, -2.77777778,
       -3.22222222, -3.66666667, -4.11111111, -4.55555556, -5.        ])

### RANDOM

In [18]:
c =np.random.random(20)
c

array([0.25652139, 0.63223532, 0.04442313, 0.52575095, 0.13299396,
       0.95522844, 0.19331841, 0.44739911, 0.71820742, 0.24073949,
       0.97694947, 0.77294814, 0.57508572, 0.80221433, 0.16013472,
       0.63583511, 0.45444252, 0.54409001, 0.31906639, 0.89593223])

In [19]:
a = np.random.random(10)
a

array([0.72155144, 0.21066118, 0.53990358, 0.94135289, 0.51046038,
       0.3421878 , 0.23418383, 0.04476831, 0.21027863, 0.53550056])

In [20]:
random_int=np.random.randint(low=20,high=55,size=10)
print(random_int)

[37 50 37 46 47 45 24 48 32 38]


In [21]:
random = np.random.randint(low=1,high=100,size = 5)
print(random)

[35 41 98 75 84]


In [22]:
np.random.randint(30,100,6)

array([81, 30, 46, 65, 67, 77], dtype=int32)

In [23]:
np.random.randint(20,100,8)

array([35, 57, 38, 46, 40, 57, 55, 33], dtype=int32)

In [4]:
import numpy as np


In [5]:
c = np.random.randint(20,100,7)
c

array([68, 57, 40, 52, 59, 33, 41], dtype=int32)

### GENERATE A 2-D ARRAY OF RANDOM INTEGERS

In [6]:
import numpy as np

In [9]:
a = np.random.randint(1,15,(4,6))
a

array([[ 7, 14,  3,  9, 10,  4],
       [12, 10,  5, 10,  8,  1],
       [ 1,  8, 11,  4, 10, 11],
       [14,  2,  5, 14, 10,  1]], dtype=int32)

In [11]:
b = np.random.randint(-20,-1,(3,4))
b

array([[ -8, -19, -13,  -8],
       [-17,  -9,  -2, -18],
       [-13,  -7, -12, -17]], dtype=int32)

In [12]:
b.shape

(3, 4)

In [16]:
b.size

12

In [17]:
b.itemsize    #its get a ite in bytes

4

In [18]:
b.nbytes

48

In [19]:
b.ndim

2

In [20]:
b.dtype

dtype('int32')

In [21]:
type(b)

numpy.ndarray

In [22]:
a = np.arange(-11,10,4)
a

array([-11,  -7,  -3,   1,   5,   9])

In [23]:
a.shape

(6,)

In [24]:
a.ndim

1

In [25]:
a.dtype

dtype('int64')

In [26]:
type(a)

numpy.ndarray

### TYPE CASTING

In [27]:
a=a.astype('float')
a

array([-11.,  -7.,  -3.,   1.,   5.,   9.])

In [30]:
np.append(a,21)

array([-11.,  -7.,  -3.,   1.,   5.,   9.,  21.])

In [31]:
np.append(a,'name')

array(['-11.0', '-7.0', '-3.0', '1.0', '5.0', '9.0', 'name'], dtype='<U32')

In [33]:
np.append(a,100)

array([-11.,  -7.,  -3.,   1.,   5.,   9., 100.])

In [35]:
a = np.append(a,100)
a

array([-11.,  -7.,  -3.,   1.,   5.,   9., 100.])

In [36]:
np.append(a,'name')

array(['-11.0', '-7.0', '-3.0', '1.0', '5.0', '9.0', '100.0', 'name'],
      dtype='<U32')

In [37]:
np.insert(a,0,21)

array([ 21., -11.,  -7.,  -3.,   1.,   5.,   9., 100.])

In [38]:
np.insert(a,3,5)

array([-11.,  -7.,  -3.,   5.,   1.,   5.,   9., 100.])

In [40]:
z = np.random.randint(1,10,(5,6))
z

array([[9, 7, 6, 7, 7, 5],
       [2, 7, 1, 8, 4, 3],
       [3, 9, 5, 3, 4, 5],
       [5, 3, 9, 7, 8, 9],
       [9, 4, 1, 6, 7, 5]], dtype=int32)

In [41]:
np.insert(z,0,4,axis=0)

array([[4, 4, 4, 4, 4, 4],
       [9, 7, 6, 7, 7, 5],
       [2, 7, 1, 8, 4, 3],
       [3, 9, 5, 3, 4, 5],
       [5, 3, 9, 7, 8, 9],
       [9, 4, 1, 6, 7, 5]], dtype=int32)

In [45]:
np.insert(z,1,0,axis=1)

array([[9, 0, 7, 6, 7, 7, 5],
       [2, 0, 7, 1, 8, 4, 3],
       [3, 0, 9, 5, 3, 4, 5],
       [5, 0, 3, 9, 7, 8, 9],
       [9, 0, 4, 1, 6, 7, 5]], dtype=int32)

In [49]:
np.insert(z,1,[1,2,3,4,5],axis = 1)


array([[9, 1, 7, 6, 7, 7, 5],
       [2, 2, 7, 1, 8, 4, 3],
       [3, 3, 9, 5, 3, 4, 5],
       [5, 4, 3, 9, 7, 8, 9],
       [9, 5, 4, 1, 6, 7, 5]], dtype=int32)

In [52]:
np.insert(z,1,[1,2,3,4,5,6],axis =0)

array([[9, 7, 6, 7, 7, 5],
       [1, 2, 3, 4, 5, 6],
       [2, 7, 1, 8, 4, 3],
       [3, 9, 5, 3, 4, 5],
       [5, 3, 9, 7, 8, 9],
       [9, 4, 1, 6, 7, 5]], dtype=int32)

### TO DELETE AN ELEMENT

In [58]:
x=np.random.randint(1,10,(2,3))
x

array([[1, 8, 9],
       [6, 2, 3]], dtype=int32)

In [59]:
s=np.delete(x,0)
s

array([8, 9, 6, 2, 3], dtype=int32)

In [60]:
s=np.delete(x,1)
s

array([1, 9, 6, 2, 3], dtype=int32)

In [61]:
s=np.delete(x,4)
s

array([1, 8, 9, 6, 3], dtype=int32)

### TO DELETE ROW WISE AND COLUMN WISE

In [62]:
x

array([[1, 8, 9],
       [6, 2, 3]], dtype=int32)

In [63]:
np.delete(x,0,axis=1)

array([[8, 9],
       [2, 3]], dtype=int32)

In [64]:
x

array([[1, 8, 9],
       [6, 2, 3]], dtype=int32)

In [67]:
np.delete(x,1,axis=0)

array([[1, 8, 9]], dtype=int32)

In [68]:
np.delete(x,2,axis=1)

array([[1, 8],
       [6, 2]], dtype=int32)

In [69]:
np.delete(x,(0,1),axis=1)

array([[9],
       [3]], dtype=int32)

In [71]:
a = np.random.randint(1,20,(4,4))
a

array([[17, 16,  6,  3],
       [17, 16,  8, 15],
       [12, 18, 17, 16],
       [12,  5,  1,  1]], dtype=int32)

In [73]:
np.delete(a,(1,0),axis=0)

array([[12, 18, 17, 16],
       [12,  5,  1,  1]], dtype=int32)

### CREATE A COPY

In [74]:
a=np.copy([3,4,5,6,7])
a

array([3, 4, 5, 6, 7])

In [75]:
a=np.array([1,2,3,4,5])
b=np.copy(a)
b

array([1, 2, 3, 4, 5])

In [76]:
a = np.array([1,2,3,4,5])
b=a.copy()
b

array([1, 2, 3, 4, 5])

### SORT

In [78]:
a=[5,6,7,8,9]
np.sort(a)

array([5, 6, 7, 8, 9])

In [80]:
b = [12,3,5,2,7,67,12,9,7]
np.sort(b)

array([ 2,  3,  5,  7,  7,  9, 12, 12, 67])

### REVERSE OR DECENTING ORDER

In [81]:
np.sort(a)[::-1]

array([9, 8, 7, 6, 5])

### SORT 2D ARRAY

In [1]:
import numpy as np

In [2]:
c=np.array([[1,2,3],[5,4,5],[3,4,6]])
np.sort(c)

array([[1, 2, 3],
       [4, 5, 5],
       [3, 4, 6]])

In [3]:
a = np.array([[3,2,4],[6,4,5],[1,8,6]])
np.sort(a)

array([[2, 3, 4],
       [4, 5, 6],
       [1, 6, 8]])

In [5]:
np.sort(a)[::-1]

array([[1, 6, 8],
       [4, 5, 6],
       [2, 3, 4]])

In [6]:
np.sort(-a)

array([[-4, -3, -2],
       [-6, -5, -4],
       [-8, -6, -1]])

In [8]:
np.sort(-c)

array([[-3, -2, -1],
       [-5, -5, -4],
       [-6, -4, -3]])

In [9]:
np.array(+c)

array([[1, 2, 3],
       [5, 4, 5],
       [3, 4, 6]])

In [10]:
np.array(c)

array([[1, 2, 3],
       [5, 4, 5],
       [3, 4, 6]])

### OR

In [11]:
a =np.random.randint(0,5,(4,5))
a

array([[4, 4, 3, 1, 2],
       [0, 4, 4, 4, 1],
       [3, 2, 1, 4, 0],
       [1, 3, 3, 4, 0]], dtype=int32)

In [15]:
a=np.array([[5,3,3,3,3],[3,5,3,3,3],[3,3,5,3,3],[3,3,3,5,3],[3,3,3,3,5]])
a

array([[5, 3, 3, 3, 3],
       [3, 5, 3, 3, 3],
       [3, 3, 5, 3, 3],
       [3, 3, 3, 5, 3],
       [3, 3, 3, 3, 5]])

In [32]:
a=np.full((5,5),(3))
a[[0,1,2,3,4],[0,1,2,3,4]]=0
a

array([[0, 3, 3, 3, 3],
       [3, 0, 3, 3, 3],
       [3, 3, 0, 3, 3],
       [3, 3, 3, 0, 3],
       [3, 3, 3, 3, 0]])

In [20]:
a=np.array([[3,9,8],[7,6,5],[9,9,0]])
b=np.array([[9,2,-1],[-7,4,4],[3,1,0]])
c=np.array([[1,2,3],[3,4,5],[8,7,6]])

In [26]:
print(a)
print(b)
print(c)
np.vstack((a,b))

[[3 9 8]
 [7 6 5]
 [9 9 0]]
[[ 9  2 -1]
 [-7  4  4]
 [ 3  1  0]]
[[1 2 3]
 [3 4 5]
 [8 7 6]]


array([[ 3,  9,  8],
       [ 7,  6,  5],
       [ 9,  9,  0],
       [ 9,  2, -1],
       [-7,  4,  4],
       [ 3,  1,  0]])

### VERTICALY JOINING

In [27]:
np.vstack((a,b))

array([[ 3,  9,  8],
       [ 7,  6,  5],
       [ 9,  9,  0],
       [ 9,  2, -1],
       [-7,  4,  4],
       [ 3,  1,  0]])

In [28]:
np.vstack((a,c))

array([[3, 9, 8],
       [7, 6, 5],
       [9, 9, 0],
       [1, 2, 3],
       [3, 4, 5],
       [8, 7, 6]])

### CONCATINATION

In [2]:
import numpy as np

In [6]:
a=np.array([[3,9,8],[7,6,5],[9,9,0]])
b=np.array([[9,2,-1],[-7,4,4],[3,1,0]])
c=np.array([[1,2,3],[3,4,5],[8,7,6]])

In [4]:
np.concatenate([a,b])

array([[ 3,  9,  8],
       [ 7,  6,  5],
       [ 9,  9,  0],
       [ 9,  2, -1],
       [-7,  4,  4],
       [ 3,  1,  0]])

### HORIZONTAL JOINING(H STACK)

In [7]:
np.hstack([a,c])

array([[3, 9, 8, 1, 2, 3],
       [7, 6, 5, 3, 4, 5],
       [9, 9, 0, 8, 7, 6]])

In [8]:
np.hstack([a,b,c])

array([[ 3,  9,  8,  9,  2, -1,  1,  2,  3],
       [ 7,  6,  5, -7,  4,  4,  3,  4,  5],
       [ 9,  9,  0,  3,  1,  0,  8,  7,  6]])

In [9]:
np.hstack([a,b])

array([[ 3,  9,  8,  9,  2, -1],
       [ 7,  6,  5, -7,  4,  4],
       [ 9,  9,  0,  3,  1,  0]])

In [10]:
np.concatenate([a,c],axis=1)

array([[3, 9, 8, 1, 2, 3],
       [7, 6, 5, 3, 4, 5],
       [9, 9, 0, 8, 7, 6]])

### D STACK

In [12]:
print(np.dstack((a,b)))

[[[ 3  9]
  [ 9  2]
  [ 8 -1]]

 [[ 7 -7]
  [ 6  4]
  [ 5  4]]

 [[ 9  3]
  [ 9  1]
  [ 0  0]]]


In [13]:
a=np.array([4,5,6,7])
b=np.array([5,0,5,2])
c=np.array([6,3,4,2])
np.dstack((a,b,c))

array([[[4, 5, 6],
        [5, 0, 3],
        [6, 5, 4],
        [7, 2, 2]]])

### RAVEL

In [14]:
c=np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14],[17,18,19,20]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [17, 18, 19, 20]])

In [16]:
c.ravel() 

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14, 17, 18, 19, 20])

### ADDITION

In [17]:
import numpy as np

In [18]:
x = np.array([3,2,4,5,6])
x

array([3, 2, 4, 5, 6])

In [26]:
x+2

array([5, 4, 6, 7, 8])

In [27]:
x/2

array([1.5, 1. , 2. , 2.5, 3. ])

In [28]:
x*2

array([ 6,  4,  8, 10, 12])

In [29]:
x-2

array([1, 0, 2, 3, 4])

In [30]:
x%2

array([1, 0, 0, 1, 0])

In [31]:
x==2

array([False,  True, False, False, False])

In [32]:
x**2

array([ 9,  4, 16, 25, 36])

In [33]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3]])
a*b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [34]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [35]:
a=np.array([[1,2,3]])
b=np.array([[1,2,3],[4,5,6]])
a*b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

### MATRIX MULTIPLICATION

In [40]:
c=np.array([1,2,3])
v=np.array([2,3,4])
np.matmul(c,v)

np.int64(20)

In [44]:
a=np.array([[1,2,3],[4,7,8]])
b=np.array([[1,2,3],[4,5,6]])
a*b

array([[ 1,  4,  9],
       [16, 35, 48]])

In [55]:
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### STATICAL OPERATION

In [47]:
z=np.array([[1,2,3],[5,9,7],[9,10,8]])
z

array([[ 1,  2,  3],
       [ 5,  9,  7],
       [ 9, 10,  8]])

In [49]:
np.max(z)

np.int64(10)

In [50]:
np.max(z)

np.int64(10)

In [51]:
np.min(z)

np.int64(1)

### MAXIMUM VALUE ROW VALUE

In [56]:
np.max(z,axis=0)

array([ 9, 10,  8])

In [58]:
np.min(z,axis=0)

array([1, 2, 3])

In [59]:
np.max(z,0)

array([ 9, 10,  8])

In [60]:
np.min(z,1)

array([1, 5, 8])

### SUM

In [61]:
np.sum([5,6,8])

np.int64(19)

In [62]:
np.sum([2,3,4])

np.int64(9)

In [63]:
np.sum([9,10,5])

np.int64(24)

### RESHAPING AND RESIZING

In [66]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
a.shape

(10,)

In [70]:
a.size

10

In [71]:
a.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
a.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
a.reshape(2,4)

ValueError: cannot reshape array of size 10 into shape (2,4)

In [77]:
a.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [78]:
z=np.arange(20,50)
z

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [79]:
z.shape

(30,)

In [80]:
z.size

30

In [82]:
z.reshape(3,10)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [87]:
z.reshape(5,6)

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [88]:
z.reshape(6,5)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### RESIZING

In [89]:
z=np.arange(11,22)
z

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [90]:
z.shape

(11,)

In [96]:
np.resize(z,(5,6))

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [98]:
np.resize(z,(4,7))

array([[11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 11, 12, 13, 14, 15, 16]])

In [99]:
np.resize(z,(8,3))

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 11, 12]])

### TO CURRENT WORKING DIRECTORY

In [100]:
import os 
os.getcwd()

'C:\\Users\\hp'

### TEXT FILE CALLING A TEXT FILE

In [101]:
import numpy as np

In [104]:
data = np.genfromtxt('numpy.txt',delimiter=',')
data

array([[1., 2., 3.],
       [4., 4., 8.],
       [7., 5., 6.]])

In [106]:
data.dtype

dtype('float64')

In [108]:
a=data.astype('float')
a

array([[1., 2., 3.],
       [4., 4., 8.],
       [7., 5., 6.]])

In [110]:
a=data.astype('int')
a

array([[1, 2, 3],
       [4, 4, 8],
       [7, 5, 6]])

In [112]:
a<3

False

In [113]:
a>5

False

In [114]:
a<5

False

In [115]:
a==5

True

### CONDITIONAL SELECTION

In [120]:
data[data>5]

array([8., 7., 6.])

In [123]:
data[(data<8)&(data>2)]

array([3., 4., 4., 7., 5., 6.])

In [124]:
data[(data>2)]

array([3., 4., 4., 8., 7., 5., 6.])

### ACCESSING TE MULTIPLE ELEMENT

In [125]:
q = np.array([3,4,5,66,7,5,8,9,89,1])
q

array([ 3,  4,  5, 66,  7,  5,  8,  9, 89,  1])

In [126]:
q[[2,4,6]]

array([5, 7, 8])

In [127]:
import numpy as np

In [129]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
a[[0,1,2],[0,1,2]]

array([1, 5, 9])

In [132]:
a[[1,2],[2,1]]

array([6, 8])

### SPLIT

In [1]:
import numpy as np

In [4]:
a = np.random.randint(1,15,(4,6))
a

array([[ 8,  5,  7,  3,  5,  7],
       [13, 12,  1, 11,  6,  4],
       [ 1,  2,  6,  3,  1,  3],
       [ 6,  1,  8, 14,  4,  9]], dtype=int32)

In [5]:
np.split(a,[2])

[array([[ 8,  5,  7,  3,  5,  7],
        [13, 12,  1, 11,  6,  4]], dtype=int32),
 array([[ 1,  2,  6,  3,  1,  3],
        [ 6,  1,  8, 14,  4,  9]], dtype=int32)]

### number of split

In [9]:
np.split(a,3,axis=1)

[array([[ 8,  5],
        [13, 12],
        [ 1,  2],
        [ 6,  1]], dtype=int32),
 array([[ 7,  3],
        [ 1, 11],
        [ 6,  3],
        [ 8, 14]], dtype=int32),
 array([[5, 7],
        [6, 4],
        [1, 3],
        [4, 9]], dtype=int32)]

In [11]:
np.split(a,4,axis=0)

[array([[8, 5, 7, 3, 5, 7]], dtype=int32),
 array([[13, 12,  1, 11,  6,  4]], dtype=int32),
 array([[1, 2, 6, 3, 1, 3]], dtype=int32),
 array([[ 6,  1,  8, 14,  4,  9]], dtype=int32)]

In [12]:
np.split(a,[1,3],axis=0)

[array([[8, 5, 7, 3, 5, 7]], dtype=int32),
 array([[13, 12,  1, 11,  6,  4],
        [ 1,  2,  6,  3,  1,  3]], dtype=int32),
 array([[ 6,  1,  8, 14,  4,  9]], dtype=int32)]

In [13]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,7]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 7]])

In [15]:
np.split(c,[1,3],axis=1)

[array([[1],
        [5],
        [9]]),
 array([[2, 3],
        [6, 7],
        [0, 1]]),
 array([[4],
        [8],
        [7]])]

In [16]:
np.split(c,[1,2],axis=1)

[array([[1],
        [5],
        [9]]),
 array([[2],
        [6],
        [0]]),
 array([[3, 4],
        [7, 8],
        [1, 7]])]

In [18]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 7]])

In [20]:
np.hsplit(c,[2])

[array([[1, 2],
        [5, 6],
        [9, 0]]),
 array([[3, 4],
        [7, 8],
        [1, 7]])]

In [23]:
np.vsplit(c,[3])

[array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 7]]),
 array([], shape=(0, 4), dtype=int64)]

### COMPARISON

In [27]:
import numpy as np

In [32]:
a=np.array([1,2,3])
b = np.array([4,5,3])
print(a,
      b)

[1 2 3] [4 5 3]


### element wise comparison

In [33]:
np.equal(a,b)

array([False, False,  True])

In [34]:
a==b

array([False, False,  True])

### comparing full array

In [36]:
np.array_equal(a,b)

False

In [39]:
x = np.array([1,2,3])     #a,x melathe element same anakil true varum
np.array_equal(a,x)

True

### ISIN()

In [42]:
a = np.array([1,2,3,4,5])
list=[1,2,5]
b=np.isin(a,list)
print(b)

[ True  True False False  True]


In [43]:
list=[3,2,1]
b=np.isin(a,list)
b

array([ True,  True,  True, False, False])

### TO AVOID WARNING

In [45]:
import warnings
warnings.filterwarnings('ignore') 

In [46]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,3,4]])
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[2 3 4]]


In [47]:
a.shape

(3, 3)

In [48]:
b.size


3

In [49]:
np.add(a,b)

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [50]:
a+b

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [51]:
np.subtract(a,b)

array([[-1, -1, -1],
       [ 2,  2,  2],
       [ 5,  5,  5]])

In [53]:
sum((a,b)) 

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

### program to get the unique elements,repeat elements are deleted

In [54]:
a = np.array([10,20,30,40,12])
a 

array([10, 20, 30, 40, 12])

In [58]:
np.unique(a) 

array([10, 12, 20, 30, 40])

In [59]:
np.sort(a)

array([10, 12, 20, 30, 40])

In [72]:
a = np.arange(12,41)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [73]:
a=a[::-1]
a

array([40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24,
       23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [75]:
empty=np.empty((0,0),int)
print(empty)

[]


In [77]:
x = np.append(empty,[1,2,3])
x

array([1, 2, 3])

In [78]:
import numpy as np

In [79]:
a = np.random.randint(2,10,(3,3))
a

array([[3, 6, 4],
       [7, 2, 8],
       [9, 2, 5]], dtype=int32)

In [82]:
a = np.array([10,12,45,65,24,10.3,2])
b = np.array([90,35,23,1,4,5,16,8,1])
a=np.concatenate([a,b])
a

array([10. , 12. , 45. , 65. , 24. , 10.3,  2. , 90. , 35. , 23. ,  1. ,
        4. ,  5. , 16. ,  8. ,  1. ])

In [84]:
a = np.unique(a)
a

array([ 1. ,  2. ,  4. ,  5. ,  8. , 10. , 10.3, 12. , 16. , 23. , 24. ,
       35. , 45. , 65. , 90. ])

In [86]:
a = np.random.randint(1,10,(2,3))
a

array([[2, 1, 8],
       [4, 9, 1]], dtype=int32)

In [87]:
a.shape

(2, 3)

In [88]:
a.size

6

In [89]:
a.dtype

dtype('int32')

In [99]:
a = np.zeros((4,4))
a[[0,1,2,3],[0,1,2,3]]=4,5,6,8
a

array([[4., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 8.]])

In [102]:
a = np.full((4,4),0)
a[[0,1,2,3],[0,1,2,3]]=4,5,6,7
a

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [103]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [104]:
a[5]=9
a

array([0., 0., 0., 0., 0., 9.])

In [105]:
a = np.array([11,12,13,14,1,16,17,18,19])
a=a[::-1]
a

array([19, 18, 17, 16,  1, 14, 13, 12, 11])

In [121]:
q = np.zeros((5,5))
q

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [122]:
q[[0,0,0,0],[1,3,5,7]]=1
q[[1,1,1,1],[0,2,4,6]]=1
q[[2,2,2,2],[1,3,5,7]]=1
q[[3,3,3,3],[0,2,4,6]]=1
q[[4,4,4,4],[1,3,5,7]]=1
q

IndexError: index 5 is out of bounds for axis 1 with size 5

In [123]:
q[1::2,::2]=1
q[::2,1::2]=1
q

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

In [3]:
import numpy as np

In [5]:
p = np.array([1,2,3,4])
q = np.array([1,2,2,3,5,6,7,8])
r = np.isin(p,q)
r

array([ True,  True,  True, False])

In [6]:
z = np.isin(p,q)
z

array([ True,  True,  True, False])

In [11]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
x = np.array([1,2,3,2,3,4,5,6])
n = np.array([3,4,2,1,3,1])
v= np.intersect1d(x,n)        # used to define same element two array
v

array([1, 2, 3, 4])

In [16]:
p = np.array([10,20,30,40,50,60,70,10,20,46])
b = np.delete(p,0)
b

array([20, 30, 40, 50, 60, 70, 10, 20, 46])

In [19]:
a = np.array([-1,-2,3,4,19,-3,4,0,3])
a[a<0]=0
a

array([ 0,  0,  3,  4, 19,  0,  4,  0,  3])

In [26]:
a = np.array([10,20,30,20,20,20,40,50,10,30,59,0,80])
np.count_nonzero(a==20)

4

### PROBLEMS OF GROUP

In [27]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [31]:
a=np.random.randint(10,20,(3,4))
a

array([[15, 15, 19, 15],
       [11, 17, 18, 10],
       [11, 13, 14, 14]], dtype=int32)

In [35]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
a = np.linspace(0,1,20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [39]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x.shape

(10,)

In [40]:
x.size

10

In [41]:
x.ndim

1

In [48]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
a=x.astype('int')
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a = np.array([
    [10,20,30,30],
    [12,10,48,23],
    [13,56,3,44]])
n=(a[1,2])
a

array([[10, 20, 30, 30],
       [12, 10, 48, 23],
       [13, 56,  3, 44]])

In [53]:
n

np.int64(48)

In [55]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
a = x[::-1]
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [62]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
a = x[x%2==0]
a

array([ 2,  4,  6,  8, 10])

In [76]:
a = x[x%1==1]
a

array([], dtype=int64)

In [77]:
a = np.random.randint(1,20,(4,4))
a

array([[15,  8, 12, 13],
       [ 9,  5, 15,  5],
       [12, 15, 10,  3],
       [ 5,  4, 11, 16]], dtype=int32)

In [78]:
np.sum(a)

np.int64(158)

In [79]:
np.mean(a)

np.float64(9.875)

In [80]:
a

array([[15,  8, 12, 13],
       [ 9,  5, 15,  5],
       [12, 15, 10,  3],
       [ 5,  4, 11, 16]], dtype=int32)

In [81]:
a.min()

np.int32(3)

In [82]:
a.max()

np.int32(16)

In [85]:
avg = np.mean(a)
avg

np.float64(9.875)

In [100]:
a = np.array([[1,2,3],[4,5,6]])
c = np.array([[3,4,5,6,7]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.append(a,4)

array([1, 2, 3, 4, 5, 6, 4])

In [104]:
c

array([[3, 4, 5, 6, 7]])

In [107]:
a+2 

array([[3, 4, 5],
       [6, 7, 8]])

In [108]:
a*2 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [130]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[4,5],
              [8,4],
             [3,4]])
c = a@b
print(c)

[[29 25]
 [74 64]]


In [131]:
b

array([[4, 5],
       [8, 4],
       [3, 4]])

In [147]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
c = a.T
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [151]:
a=np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [153]:
a = np.zeros((4,4))
a[[0,1,2,3],[0,1,2,3]]=1
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [156]:
a = np.random.randint(10,100,(5,5))
a


array([[69, 14, 28, 64, 44],
       [69, 54, 92, 61, 98],
       [28, 47, 70, 51, 92],
       [65, 57, 94, 49, 94],
       [60, 37, 67, 31, 55]], dtype=int32)

In [165]:
c = a[a>50]
c

array([69, 64, 69, 54, 92, 61, 98, 70, 51, 92, 65, 57, 94, 94, 60, 67, 55],
      dtype=int32)

In [166]:
c = [a>50]
c

[array([[ True, False, False,  True, False],
        [ True,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [ True,  True,  True, False,  True],
        [ True, False,  True, False,  True]])]

In [168]:
a[a%2==0]=-1
a

array([[69, -1, -1, -1, -1],
       [69, -1, -1, 61, -1],
       [-1, 47, -1, 51, -1],
       [65, 57, -1, 49, -1],
       [-1, 37, 67, 31, 55]], dtype=int32)

In [170]:
asc = np.sort(a)
asc

array([[-1, -1, -1, -1, 69],
       [-1, -1, -1, 61, 69],
       [-1, -1, -1, 47, 51],
       [-1, -1, 49, 57, 65],
       [-1, 31, 37, 55, 67]], dtype=int32)

In [172]:
desc = np.sort(a[::-1])
desc

array([[-1, 31, 37, 55, 67],
       [-1, -1, 49, 57, 65],
       [-1, -1, -1, 47, 51],
       [-1, -1, -1, 61, 69],
       [-1, -1, -1, -1, 69]], dtype=int32)

In [173]:
a = np.random.randint(1,20,(4,4))
a

array([[14,  3, 10, 11],
       [14, 17, 19, 11],
       [ 5, 15, 15, 11],
       [11, 16,  5, 13]], dtype=int32)

In [174]:
np.vstack(a)

array([[14,  3, 10, 11],
       [14, 17, 19, 11],
       [ 5, 15, 15, 11],
       [11, 16,  5, 13]], dtype=int32)

In [175]:
np.hstack(a)

array([14,  3, 10, 11, 14, 17, 19, 11,  5, 15, 15, 11, 11, 16,  5, 13],
      dtype=int32)

In [178]:
a = np.random.randint(1,10,(4,6))
a

array([[5, 2, 8, 1, 7, 3],
       [2, 3, 9, 7, 5, 6],
       [9, 6, 7, 7, 8, 9],
       [8, 6, 7, 2, 8, 5]], dtype=int32)

In [179]:
np.split(a,[2])

[array([[5, 2, 8, 1, 7, 3],
        [2, 3, 9, 7, 5, 6]], dtype=int32),
 array([[9, 6, 7, 7, 8, 9],
        [8, 6, 7, 2, 8, 5]], dtype=int32)]

In [180]:
np.unique(a)

array([1, 2, 3, 5, 6, 7, 8, 9], dtype=int32)

In [1]:
import numpy as np

In [5]:
a = np.array([[1,2],
              [4,5]])
b = np.array([[3,4,5],
              [7,8,9]])
c = a@b
print(c)

[[17 20 23]
 [47 56 65]]


In [7]:
v = np.intersect1d(a,b)
v

array([4, 5])

In [10]:
np.ravel(a)

array([1, 2, 4, 5])

In [11]:
a.ravel()

array([1, 2, 4, 5])